# Generated by Django 5.2.2 on 2025-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True)),
                ('url', models.CharField(max_length=100)),
                ('json_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True)),
                ('url', models.CharField(max_length=100)),
                ('json_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True)),
                ('url', models.CharField(max_length=100)),
                ('json_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
            },
        ),
    ]
