# Generated by Django 5.2.2 on 2025-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('url', models.CharField(max_length=100)),
                ('using', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'エンドポイント',
                'verbose_name_plural': 'エンドポイント一覧',
            },
        ),
    ]
